server:
  servlet:
    context-path: /auth

spring:
  application:
    name: mssc-auth
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enable: true

eureka:
  instance:
    hostname: mssc-auth
    preferIpAddress: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 60000

queue:
  name: email-notification
  exchange: direct-exchange
  key: test-key