spring:
  application:
    name: mssc-auth
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: secret_token
  expiration: 60000

queue:
  name: email-notification
  exchange: direct-exchange
  key: test-key