server:
  port: 9090

spring:
  application:
    name: mssc-gateway
  cloud:
    gateway:
      routes:
        - id: mssc-auth
          uri: lb://mssc-auth
          predicates:
            - Path=/auth/api/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}