server:
  port: 8081

spring:
  application:
    name: mssc-notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

queue:
  name: email-notification